// Generated by gencpp from file robbie_stability/Contact.msg
// DO NOT EDIT!


#ifndef ROBBIE_STABILITY_MESSAGE_CONTACT_H
#define ROBBIE_STABILITY_MESSAGE_CONTACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace robbie_stability
{
template <class ContainerAllocator>
struct Contact_
{
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
    : shank(false)
    , lhm(false)
    , stabilizer(false)
    , stabilizer_on()
    , shank_on()
    , lhm_on()
    , stabilizer_location()
    , shank_location()
    , lhm_location()  {
    }
  Contact_(const ContainerAllocator& _alloc)
    : shank(false)
    , lhm(false)
    , stabilizer(false)
    , stabilizer_on(_alloc)
    , shank_on(_alloc)
    , lhm_on(_alloc)
    , stabilizer_location(_alloc)
    , shank_location(_alloc)
    , lhm_location(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _shank_type;
  _shank_type shank;

   typedef uint8_t _lhm_type;
  _lhm_type lhm;

   typedef uint8_t _stabilizer_type;
  _stabilizer_type stabilizer;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _stabilizer_on_type;
  _stabilizer_on_type stabilizer_on;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shank_on_type;
  _shank_on_type shank_on;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lhm_on_type;
  _lhm_on_type lhm_on;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _stabilizer_location_type;
  _stabilizer_location_type stabilizer_location;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _shank_location_type;
  _shank_location_type shank_location;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _lhm_location_type;
  _lhm_location_type lhm_location;




  typedef boost::shared_ptr< ::robbie_stability::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robbie_stability::Contact_<ContainerAllocator> const> ConstPtr;

}; // struct Contact_

typedef ::robbie_stability::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::robbie_stability::Contact > ContactPtr;
typedef boost::shared_ptr< ::robbie_stability::Contact const> ContactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robbie_stability::Contact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robbie_stability::Contact_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robbie_stability

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'robbie_stability': ['/home/moyin/dev/autonomous_controllers/src/robot_controllers/robbie_stability/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robbie_stability::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robbie_stability::Contact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robbie_stability::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robbie_stability::Contact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robbie_stability::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robbie_stability::Contact_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robbie_stability::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "031fc837dcc9ed46474cb01cba5abfbd";
  }

  static const char* value(const ::robbie_stability::Contact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x031fc837dcc9ed46ULL;
  static const uint64_t static_value2 = 0x474cb01cba5abfbdULL;
};

template<class ContainerAllocator>
struct DataType< ::robbie_stability::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robbie_stability/Contact";
  }

  static const char* value(const ::robbie_stability::Contact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robbie_stability::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool shank\n\
bool lhm\n\
bool stabilizer\n\
\n\
string stabilizer_on\n\
string shank_on\n\
string lhm_on\n\
\n\
geometry_msgs/Point stabilizer_location\n\
geometry_msgs/Point shank_location\n\
geometry_msgs/Point lhm_location\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robbie_stability::Contact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robbie_stability::Contact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shank);
      stream.next(m.lhm);
      stream.next(m.stabilizer);
      stream.next(m.stabilizer_on);
      stream.next(m.shank_on);
      stream.next(m.lhm_on);
      stream.next(m.stabilizer_location);
      stream.next(m.shank_location);
      stream.next(m.lhm_location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robbie_stability::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robbie_stability::Contact_<ContainerAllocator>& v)
  {
    s << indent << "shank: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shank);
    s << indent << "lhm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lhm);
    s << indent << "stabilizer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stabilizer);
    s << indent << "stabilizer_on: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.stabilizer_on);
    s << indent << "shank_on: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shank_on);
    s << indent << "lhm_on: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lhm_on);
    s << indent << "stabilizer_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.stabilizer_location);
    s << indent << "shank_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.shank_location);
    s << indent << "lhm_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.lhm_location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBBIE_STABILITY_MESSAGE_CONTACT_H
